### PR TITLE
Fix typo in readme

### PR DESCRIPTION
**Pull request by jyn514**

### CODE REVIEW

**Review by MarijnS95 — CHANGES_REQUESTED** [review]
https://github.com/microsoft/windows-docs-rs/blob/9d4264c6803f29ea0f0df22a22c95fbee55ccf6f/crates/bindings/Cargo.toml#L2

All the bindings found in the `.winmd` metadata file are collected in that `bindings` crate. ~The default / internal bindings used by the `windows` crate sit in this `windows_bindings` crate instead:~

~https://github.com/microsoft/windows-rs/tree/master/crates/bindings~

~I think you intended to _add_ `-p windows_bindings` while leaving `-p bindings` intact? I'm missing the explanation and justification in the commit-message and title here.~

EDIT: The `windows_bindings` crate is merely a runnable binary that emits a minimal subset of the Windows API (generated from the metadata) into `src/bindings.rs` for use in the core `windows` crate to implement basic functionality and utilities.

**Comment by jyn514** [comment]
@MarijnS95 hmm, maybe this is a linux-only thing? I got a hard error trying to document this on linux:
```
$ cargo doc --no-deps -p windows -p bindings
error: package ID specification `bindings` did not match any packages
```

**Comment by MarijnS95** [comment]
@jyn514 The README is deceiving here. There's no workspace, so `-p` only works when inside that crate (and is then used to select a specific subset of dependencies to include in the built docs, instead of everything). The path in the ` ```console ` here sneakily indicates the user is in the `crates\bindings` directory. IMO this crate should just have a `[workspace]` `Cargo.toml` root file instead.

**Comment by jyn514** [comment]
I am in the bindings directory.
```
[nix-shell:~/.../crates/bindings]$ pwd
/home/joshua/windows-rs/crates/bindings
[nix-shell:~/.../crates/bindings]$ cargo doc --no-deps -p windows -p bindings
error: package ID specification `bindings` did not match any packages
```

**Comment by jyn514** [comment]
Oh I see, it expects me to be in the `windows-docs-rs` repo, not `windows-rs`. That's confusing - do you know why the source is different? How is windows-docs-rs generated?

**Comment by MarijnS95** [comment]
> `/home/joshua/windows-rs/crates/bindings`

Are you sure that's [`crates/bindings` of `windows-docs-rs`](https://github.com/microsoft/windows-docs-rs/tree/master/crates/bindings), not [that of `windows-rs`](https://github.com/microsoft/windows-rs/tree/master/crates/bindings)?

EDIT: Looks like you found out the same :)

**Comment by MarijnS95** [comment]
> Oh I see, it expects me to be in the `windows-docs-rs` repo, not `windows-rs`. That's confusing - do you know why the source is different? How is windows-docs-rs generated?

Sorry, I don't think I fully understand this question. `windows-docs-rs` is a _helper_ crate to generate documentation for the `windows` crate and every binding currently known in the metadata file. Running the command in the README in that folder should be enough, but the result is massive and only publicly available at https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/. This crate is (afaik for that size reason) not published - otherwise it'll also serve as "the global cover-it-all-but-extremely-slow" Windows API crate, superseding winapi (that's a massive but different issue entirely, covered in https://github.com/microsoft/windows-rs/issues/432).

**Comment by jyn514** [comment]
Right, I understand all that, but my question is exactly *how* they're different - is there a way to generate the windows-docs-rs repo from windows-rs? I assume you're not maintaining almost identical projects in parallel.

**Comment by MarijnS95** [comment]
> Right, I understand all that, but my question is exactly _how_ they're different - is there a way to generate the windows-docs-rs repo from windows-rs? I assume you're not maintaining almost identical projects in parallel.

These projects are not identical at all - which should be obvious from browsing through a couple source files? Again, I don't think I have understood your question but I'll try to answer it to the best of my abilities:

See https://github.com/microsoft/windows-docs-rs/blob/9d4264c6803f29ea0f0df22a22c95fbee55ccf6f/crates/modules/src/main.rs#L6-L14

The `modules` crate uses `windows-rs` to walk through the default `.winmd` metadata file, printing out every (generatable) namespace in the process. These end up in https://github.com/microsoft/windows-docs-rs/blob/master/crates/bindings/build.rs, which are subsequently turned into code (`$OUT_DIR/windows.rs`) through `windows::build!` (the only difference being that crate users of windows-rs use a significantly reduced list since all this codegen is expensive - slow).

Generating docs over this `bindings` crate gives us a nice, indexed, searchable overview of all the Rust bindings that _can_ be generated by `windows-rs`'s bindings generator. The advantage over searching Microsoft's C docs is that everything is moved into specific namespaces which are not listed there, and the Rust function signatures can be quite different thanks to smart codegen in favour of safety and simplicity.

**Comment by jyn514** [comment]
You answered my question, thanks :) this works by telling windows-rs to generate all the modules it knows about.

**Comment by MarijnS95** [comment]
@jyn514 Great, glad I could help!

I have to make one correction to my original comment:

> The default / internal bindings used by the `windows` crate sit in this `windows_bindings` crate instead:
> 
> https://github.com/microsoft/windows-rs/tree/master/crates/bindings
> 
> I think you intended to _add_ `-p windows_bindings` while leaving `-p bindings` intact? I'm missing the explanation and justification in the commit-message and title here.

This is not true. `windows_bindings` is merely a runnable binary that generates Rust code from the metadata (much like the "generated" `crates/bindings/build.rs` here, but for a minimal subset of the Windows API rather than all of it), the output file sits right in the root of `windows-rs` in `src/bindings.rs`, and is _not_ loaded through another crate (that I previously punted to be `windows_bindings`).

**Comment by kennykerr** [comment]
Hey @jyn514 - did you get it working? 

This repo exists just to generate the docs in a manual fashion on my local machine as its too slow to automate in any other way.

**Comment by jyn514** [comment]
@kennykerr no, it looks like this has some hard-coded paths. Have you considered using `git = "..."` instead of pointing to a local path?
```
$ cargo doc --no-deps -p windows -p bindings --target-dir ../../docs
error: failed to get `windows` as a dependency of package `bindings v0.1.0 (/home/joshua/windows-docs-rs/crates/bindings)`

Caused by:
  failed to load source for dependency `windows`

Caused by:
  Unable to update /git/windows-rs

Caused by:
  failed to read `/git/windows-rs/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```
Although I suspect it will only "work" after that in the sense that it will do nothing, since windows-rs is just an empty crate on linux AFAIK

**Comment by MarijnS95** [comment]
> Although I suspect it will only "work" after that in the sense that it will do nothing, since windows-rs is just an empty crate on linux AFAIK

Fortunately this is far from true: The entire windows-rs crate works flawless on Linux up until the linking stage - but that isn't used for documentation. Even better: I'm [using windows-rs](https://github.com/MarijnS95/windows-rs/commits/dxc) (with some slight modifications) to call into libraries with a COM interface on Linux (thanks for bringing us this far by the way, Kenny!).

I think I managed to generate some parts of the documentation on Linux as well, should work just fine :)

**Comment by kennykerr** [comment]
Yes, you can run the entirety of windows-docs-rs on Linux - its just not obvious how because its tailored for me to build it locally from my dev clone of windows-rs before I publish a new build to GitHub for validation. But if its something you'd like to use to test I'd be more than happy to update the dependencies to point to git instead.

**Comment by jyn514** [comment]
> But if its something you'd like to use to test I'd be more than happy to update the dependencies to point to git instead.

Yup, that would be super useful, thank you!

**Comment by kennykerr** [comment]
Will do.

**Comment by kennykerr** [comment]
https://github.com/microsoft/windows-docs-rs has been updated - both crates should now build directly against the latest published version of the `windows` crate. Simply build `crates\bindings` - I don't have a Linux machine to test on but in theory that should now "just work". 🤞

**Comment by jyn514** [comment]
Yup, I was able to build the docs on Linux after that change :) thank you!

(for the curious, here is the output of -Ztime-passes on `bindings`, I hope to take a closer look at it this weekend)
<details>

```
 Documenting bindings v0.1.0 (/home/joshua/windows-docs-rs/crates/bindings)
     Running `rustdoc --edition=2018 --crate-type lib --crate-name bindings src/lib.rs -o /home/joshua/windows-docs-rs/crates/bindings/../../docs/doc --error-format=json --json=diagnostic-rendered-ansi -Ztime-passes -Zself-profile -L dependency=/home/joshua/windows-docs-rs/crates/bindings/../../docs/debug/deps --extern windows=/home/joshua/windows-docs-rs/crates/bindings/../../docs/debug/deps/libwindows-a15d74106bae8661.rmeta --crate-version 0.1.0`
time:   0.000; rss:   37MB ->   38MB (   +1MB)	parse_crate
time:   0.000; rss:   38MB ->   38MB (   +0MB)	attributes_injection
time:   0.000; rss:   38MB ->   38MB (   +0MB)	plugin_loading
time:   0.000; rss:   38MB ->   38MB (   +0MB)	plugin_registration
time:   0.000; rss:   40MB ->   40MB (   +0MB)	crate_injection
time:  34.383; rss:   40MB -> 7450MB (+7410MB)	expand_crate
time:   0.000; rss: 7450MB -> 7450MB (   +0MB)	check_unused_macros
time:  34.383; rss:   40MB -> 7450MB (+7410MB)	macro_expand_crate
time:   0.000; rss: 7450MB -> 7450MB (   +0MB)	maybe_building_test_harness
time:   1.183; rss: 7450MB -> 7447MB (   -3MB)	AST_validation
time:   0.000; rss: 7447MB -> 7447MB (   +0MB)	maybe_create_a_macro_crate
time:   0.007; rss: 7447MB -> 7447MB (   +0MB)	finalize_imports
time:   0.557; rss: 7447MB -> 7480MB (  +33MB)	finalize_macro_resolutions
time:  13.025; rss: 7480MB -> 9227MB (+1747MB)	late_resolve_crate
time:   0.000; rss: 9227MB -> 9227MB (   +0MB)	resolve_main
time:   0.819; rss: 9227MB -> 9227MB (   +0MB)	resolve_check_unused
time:   0.000; rss: 9227MB -> 9227MB (   +0MB)	resolve_report_errors
time:   0.756; rss: 9227MB -> 9227MB (   +0MB)	resolve_postprocess
time:  15.164; rss: 7447MB -> 9227MB (+1779MB)	resolve_crate
time:   1.003; rss: 9227MB -> 9227MB (   +0MB)	complete_gated_feature_checking
time:  51.734; rss:   38MB -> 9227MB (+9189MB)	configure_and_expand
time:   0.000; rss: 9227MB -> 9227MB (   +0MB)	load_extern_crates
time:   0.000; rss: 9227MB -> 9227MB (   +0MB)	prepare_outputs
time:  19.425; rss: 9227MB -> 12497MB (+3271MB)	hir_lowering
time:   2.255; rss: 12497MB -> 12517MB (  +19MB)	early_lint_checks
time:   2.407; rss: 12517MB -> 11600MB ( -916MB)	drop_ast
time:   0.102; rss: 11877MB -> 11877MB (   +0MB)	setup_global_ctxt
time:  79.936; rss: 11877MB -> 11242MB ( -635MB)	item_types_checking
time:  22.218; rss: 11242MB -> 11488MB ( +245MB)	crate_lints
time:   0.000; rss: 11488MB -> 11488MB (   +0MB)	module_lints
time:  22.219; rss: 11242MB -> 11488MB ( +245MB)	missing_docs
time:   4.786; rss: 11488MB -> 11565MB (  +77MB)	check_mod_attrs
time:   3.275; rss: 11614MB -> 12386MB ( +772MB)	clean_crate
time:  21.885; rss: 12386MB -> 13843MB (+1456MB)	collect_synthetic_impls
time:   0.169; rss: 13843MB -> 13867MB (  +25MB)	collect_items_for_trait_impls
time:  34.827; rss: 12386MB -> 14366MB (+1980MB)	collect-trait-impls
time:   0.309; rss: 14366MB -> 14366MB (   +0MB)	unindent-comments
time:   6.531; rss: 14366MB -> 14384MB (  +18MB)	check-private-items-doc-tests
time:   1.151; rss: 14384MB -> 14385MB (   +1MB)	strip-hidden
time:   0.962; rss: 14385MB -> 14386MB (   +1MB)	strip-private
time:   1.542; rss: 14386MB -> 14376MB (  -10MB)	collect-intra-doc-links
time:   0.284; rss: 14376MB -> 14371MB (   -4MB)	check-code-block-syntax
time:   0.277; rss: 14371MB -> 14371MB (   +0MB)	check-invalid-html-tags
time:   0.285; rss: 14371MB -> 14371MB (   +0MB)	propagate-doc-cfg
time:   0.296; rss: 14371MB -> 14372MB (   +0MB)	check-bare-urls
time:   3.455; rss: 14372MB -> 14871MB ( +499MB)	create_format_cache
time: 161.880; rss: 11877MB -> 12741MB ( +864MB)	run_global_ctxt
time:   7.654; rss: 12741MB -> 12691MB (  -50MB)	create_renderer(html)
time:   0.302; rss: 13103MB -> 13097MB (   -6MB)	renderer_after_krate(html)
time:  79.360; rss: 12741MB -> 12756MB (  +14MB)	render_html
time:   0.000; rss: 12737MB -> 12737MB (   +0MB)	serialize_dep_graph
time:   1.094; rss: 12737MB -> 9045MB (-3692MB)	free_global_ctxt
   Completed bindings v0.1.0 lib (doc) in 320.0s
```

</details>

**Pull request closed without merging**
